fix(ui): fix wrong text color
snapshot-labs/sx-monorepo pull request #273
Opened 2024-04-13 20:00 UTC by wa0x6e

### Summary

Closes: #269 

Fix wrong text color

### How to test

1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x504dd8da2930579b0aeb88946396140a74ce59fb8ccad5902cf1bfd2d33f1e07
2. The rank label in the choice form should have the correct text color on light and dark theme

![Screenshot 2024-04-13 at 23 59 50](https://github.com/snapshot-labs/sx-monorepo/assets/495709/ddba5346-f66c-4a48-a56d-974e909e1119)
![Screenshot 2024-04-13 at 23 59 54](https://github.com/snapshot-labs/sx-monorepo/assets/495709/c3d1be50-7e94-4ceb-80ef-dd2382eca02d)

2024-04-13 20:05 UTC, bonustrack approved these changes
utACK

2024-04-13 20:06 UTC, bonustrack requested changes
Wait

2024-04-13 20:07 UTC, bonustrack commented on apps/ui/src/components/ProposalVoteRankedChoice.vue
> +            class="h-[18px] min-w-[18px] rounded-full leading-[18px] text-[13px] text-skin-text bg-skin-border px-2 text-center inline-block"
It should use text-skin-link similar as the vote count
```suggestion
            class="h-[18px] min-w-[18px] rounded-full leading-[18px] text-[13px] text-skin-link bg-skin-border px-2 text-center inline-block"
```

2024-04-14 19:55 UTC, bonustrack approved these changes
tACK

2024-04-15 13:02 UTC, Sekhmet approved these changes
tACK

2024-04-15 13:04 UTC, merged