fix: fix abstain vote button color
snapshot-labs/sx-monorepo pull request #401
Opened 2024-06-13 20:52 UTC by wa0x6e

### Summary

Closes: #

### How to test

1.

### To-Do

- [ ]

2024-06-13 21:22 UTC, bonustrack approved these changes
tACK

2024-06-14 15:11 UTC, Sekhmet commented
We might be actually messing up something with choice values (2 should be abstain, but here it's 0). Taking a look.

2024-06-14 15:27 UTC, Sekhmet requested changes
Blocking this PR until https://github.com/snapshot-labs/highlight/pull/19 is investigated, but if it's confirmed this PR won't be needed (it also looks like this vote was actually Against, not Abstain).

2024-06-14 15:46 UTC, Sekhmet commented
Without this PR after highlight change:
voting abstain:
<img width="1580" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/1968722/ccb217a0-b54f-418d-8aaf-058c93aabaae">

voting against:
<img width="1578" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/1968722/f2afd6b2-8069-4a57-a5b3-eb6d172f9ab9">


voting for:
<img width="1920" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/1968722/4597ccf0-b823-475b-a8dd-3cb4a352aa44">

So this PR is not needed, sorry Wan 😆

2024-06-14 15:46 UTC, closed without merging