feat: add space controller edition for offchain spaces
snapshot-labs/sx-monorepo pull request #776
Opened 2024-09-16 15:57 UTC by Sekhmet

### Summary

Changes:
 - check `snapshot` record on ENS to detect real controller (as opposed to owner)
 - add ability to change controller if you are a space owner

### How to test

1. Go to your offchain space settings.
2. Change controller.

2024-09-16 17:10 UTC, ChaituVR requested changes

2024-09-16 17:10 UTC, ChaituVR commented on apps/ui/src/helpers/ens.ts
> +  if (snapshotRecord) return snapshotRecord;
There is another case, where spaces can have a text record like 
```
ipns://storage.snapshot.page/registry/<CONTROLLER_ADDRESS>/aave.eth
```

https://app.ens.domains/aave.eth?tab=records

In this case `0x60C8dC4762b217b4A00FF1824111077f331B1FbF` will be controller. but we resolve this
<img width="204" alt="image" src="https://github.com/user-attachments/assets/c8fbcd41-0482-44e9-9fcf-c1044a53de9c">


Refer to https://github.com/snapshot-labs/snapshot.js/blob/master/src/utils.ts#L628-L645 on how to parse the URI

2024-09-16 17:10 UTC, ChaituVR commented on apps/ui/src/helpers/ens.ts
> +  if (snapshotRecord) return snapshotRecord;
Refer
https://github.com/snapshot-labs/snapshot.js/blob/master/src/utils.ts#L536-L578

There is a chance that a ENS name can change its resolver, so we should get resolver first, to see if we support it. and then read text record

2024-09-17 13:52 UTC, Sekhmet commented on apps/ui/src/networks/offchain/actions.ts
> +  chainId: 1 | 11155111
I didn't want to use specific type (to ENS) in generic context (just network) - thought it didn't make sense to define supported offchain networks in context of ENS networks, but wanted to have valid types anyway (and to know when they are no longer compatible).

2024-09-18 23:06 UTC, bonustrack approved these changes
I haven't tried all edge case but UX is good to me

2024-09-19 07:03 UTC, ChaituVR approved these changes
tAck

Maybe we should display settings tab to owner also so they can change controller
<img width="230" alt="Untitled 2" src="https://github.com/user-attachments/assets/53257b28-09e3-4a0f-b100-8257cdfb6cba">

2024-09-19 12:31 UTC, merged