feat: add members settings for offchain spaces
snapshot-labs/sx-monorepo pull request #781
Opened 2024-09-17 11:01 UTC by Sekhmet

### Summary

This PR adds members settings to offchain spaces.

### How to test

1. Go to settings of offchain space you control.
2. You can go to members.
3. You can modify members as you want and save it.

### Screenshots

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/16c68680-a120-481e-8ab0-61b67df1a89d">
<img width="602" alt="image" src="https://github.com/user-attachments/assets/9cf2bd98-0b43-4f0f-939e-1d1d07b277ad">

2024-09-17 11:11 UTC, bonustrack commented
Some comments:

- When I add a wrong address like `0xB97f8Fa70807bBb26e42Af8271DB05B3c04BA3B1` it empty the section
- When I change a role or add a member, it doesn't show me the bottom nav to save changes.
- Ideally the admins should also see a link to the settings from the space menu.

2024-09-17 12:43 UTC, bonustrack approved these changes
Works well now, tACK

2024-09-17 13:51 UTC, ChaituVR requested changes
Changing to controller address doesn't allow me to update admins unless i reload

![Sep-17-2024 19-19-21](https://github.com/user-attachments/assets/f2d0c433-a171-4d86-8c96-6cf5cca5cd8d)

After reload
<img width="674" alt="Untitled 2" src="https://github.com/user-attachments/assets/13ee1aa8-d9c1-4267-a29c-2c5d12958a75">

2024-09-17 14:03 UTC, ChaituVR commented on apps/ui/src/helpers/validation.ts
I think we should show a error instead of "Invalid format."
<img width="432" alt="Untitled 5" src="https://github.com/user-attachments/assets/c50a1933-01ed-4545-b28a-756d0bdbc107">

<img width="398" alt="Untitled 4" src="https://github.com/user-attachments/assets/fffbe791-b064-4017-b349-b46a6bcbd619">

2024-09-17 15:02 UTC, wa0x6e commented
Address splitting have some issues

Try with `0x757a20E145435B5bDaf0E274987653aeCD47cf37 , 0xab54624A67E8c018a06B176bAAE76a40a385A464`

It gives:

![Screenshot 2024-09-18 at 00 00 11](https://github.com/user-attachments/assets/780d4704-1b38-4789-8a16-0c1cb5b94e22)

- The first address is shown as starting with `0x0000` and not `0x757`
- The second address still has the whitespace at the beginning, with explorer address: https://etherscan.io/address/%200xab54624A67E8c018a06B176bAAE76a40a385A464

2024-09-17 15:04 UTC, wa0x6e commented
And the figma is using an input, but I feel like a textarea is better here, like on for the whitelist strategies or voting power, since we're accepting multiple addresses.

The current input is not even big enough to show a full single address

2024-09-18 02:32 UTC, wa0x6e approved these changes
tAck

2024-09-18 04:34 UTC, ChaituVR approved these changes
tAck

2024-09-18 10:02 UTC, merged