feat: add Advanced settings for offchain spaces.
snapshot-labs/sx-monorepo pull request #789
Opened 2024-09-19 13:10 UTC by Sekhmet

### Summary

Adding advanced settings page for offchain spaces with following options:
- Sub-spaces (parent and child spaces)
- Terms of services
- Custom domain
- Hide from homepage
- Delete space

Had to make some adjustments from the design, as not everything was clear:
- Not extraneous modals for parent-space, sub-space, custom-domain (in designs we have input, but also modal that opens for you to type in, which I'm not sure makes sense, here I just use inputs directly avoiding modals.
- Designs didn't cover how already added sub-spaces should look like, so I improvised.
- No tooltip for custom domain input as we don't have it either on v1 so I didn't have text to use.

Closes: #

### How to test

1. Create new space (if you want to delete it, **you will lose ability to recreate space under that domain**).
2. Go to your space, enter settings, you can modify advanced settings.
3. You can delete your space.

### Screenshots

![localhost_8080_ (9)](https://github.com/user-attachments/assets/32a672de-fd48-421f-8b3c-df42c844d334)

2024-09-19 13:11 UTC, Sekhmet commented on apps/ui/src/views/Space/Settings.vue
> +      description="Office ipsum you must be muted. Boy ocean define crank new."
@bonustrack will need text for this section.

2024-09-20 17:59 UTC, bonustrack reviewed
It should be possible to add both a main space, and a sub spaces, it's not one or the other.

Also ideally we shouldn't allow duplicate for sub spaces.

2024-09-20 17:59 UTC, bonustrack commented on apps/ui/src/components/FormSpaceAdvanced.vue
> +    github after you have created the space.
```suggestion
    GitHub after you have created the space.
```

2024-09-21 14:05 UTC, wa0x6e requested changes
![Screenshot 2024-09-21 at 18 03 30](https://github.com/user-attachments/assets/3d72ea63-fb0f-4230-a13c-6686aa1631f1)

Disabled danger button should have disabled border color

2024-09-21 14:08 UTC, wa0x6e commented on apps/ui/src/components/Ui/Message.vue
> +        <IH-arrow-top-right-on-square />
This is indeed from Figma, but on v2, we're now using the 45deg arrow without the square box for external link.

Better to follow the v2 format

2024-09-21 14:25 UTC, wa0x6e requested changes
The parent and child space input form should have a loading indicator

![Screenshot 2024-09-21 at 18 24 54](https://github.com/user-attachments/assets/8d9edcc7-da72-4721-a583-737ed7015419)

2024-09-21 14:28 UTC, wa0x6e requested changes
Dirtying any fields in the new ADVANCED tab is not showing the bottom toolbar with SAVE button

2024-09-21 14:30 UTC, wa0x6e reviewed
Should prevent duplicate in child spaces

![Screenshot 2024-09-21 at 18 30 22](https://github.com/user-attachments/assets/c14351a1-6019-4d45-97ff-c27ad870dafe)

2024-09-21 14:58 UTC, wa0x6e requested changes

2024-09-21 14:58 UTC, wa0x6e commented on apps/ui/src/composables/useActions.ts
> +      throw new Error(`${web3.value.type} is not supported for this actions`);
```suggestion
      throw new Error(`${web3.value.type} is not supported for this action`);
```

2024-09-21 14:59 UTC, wa0x6e commented
> It should be possible to add both a main space, and a sub spaces, it's not one or the other.
> 
> Also ideally we shouldn't allow duplicate for sub spaces.

Seems like on v1, it's one or the other, both are not possible

2024-09-21 15:06 UTC, wa0x6e commented
![Screenshot 2024-09-21 at 19 05 44](https://github.com/user-attachments/assets/c047c300-a8ba-4ec1-b975-fe6d232c9d12)

Space between checkbox and label seen insufficient

2024-09-23 12:47 UTC, Sekhmet commented
> The parent and child space input form should have a loading indicator

Updated it to have similar space validation UX as v1.

> Dirtying any fields in the new ADVANCED tab is not showing the bottom toolbar with SAVE button

Should be fixed now.

> Space between checkbox and label seen insufficient

Followed designs there, but I agree this doesn't look good, increased it to `gap-2`.

2024-09-23 12:47 UTC, Sekhmet commented
> It should be possible to add both a main space, and a sub spaces, it's not one or the other.

As Wan mentioned this replicates v1 UI that prevents configuring both parent and sub-spaces at the same time. I can remove that validation if we confirm that's what we want.

2024-09-23 14:42 UTC, wa0x6e requested changes
The domain name field is missing the length validation

![Screenshot 2024-09-23 at 18 39 50](https://github.com/user-attachments/assets/c87b26f8-e014-42b4-99b3-7a51dd0ccf10)

Putting something over the char limit does not show any errors.

And it's not on v1, but maybe it's time to also put a proper domain name validation on this field, since we'll be using it automatically for the whitelabel

On v1, there's a human manual validation, but we're moving away from that for v2

2024-09-23 14:58 UTC, wa0x6e requested changes
When putting an invalid space name in the parent space, it shows an error.

But it we change tab, and go back to advanced, the error state is gone.

There seems to be a query to check if the space is valid (loading icon on the input on tab change), but the error state is not being restored

2024-09-23 15:02 UTC, wa0x6e reviewed
![Screenshot 2024-09-23 at 19 01 42](https://github.com/user-attachments/assets/42ff503c-b527-434c-82bb-a6840911a8e8)

Shouldn't the message be different ?

2024-09-23 15:08 UTC, Sekhmet commented
> When putting an invalid space name in the parent space, it shows an error.
> But it we change tab, and go back to advanced, the error state is gone.
> There seems to be a query to check if the space is valid (loading icon on the input on tab change), but the error state is not being restored

It's broken app-wide, we should fix it properly, but not really belongs in this PR, we can workaround it by using `v-show` which is not ideal (used it there for now).
https://github.com/snapshot-labs/sx-monorepo/issues/573

2024-09-23 15:13 UTC, Sekhmet commented
> And it's not on v1, but maybe it's time to also put a proper domain name validation on this field, since we'll be using it automatically for the whitelabel

What you consider proper domain name validation? I think anything "proper" would be out of scope of this PR.

2024-09-23 15:14 UTC, wa0x6e reviewed
When reaching the max number of sub-spaces, the sub-space form is still accepting value, and validating space name.

But does not show any error when the space name is valid. I think it should show the error about reaching the max number of sub-spaces

2024-09-23 15:17 UTC, wa0x6e commented
> out of scope of this PR.

For now, just `alphanum`, `.`, `_` and `-` will cover 100% of our existing list (https://github.com/snapshot-labs/snapshot-spaces/blob/master/spaces/domains.json) we can optimize later

2024-09-23 15:29 UTC, wa0x6e reviewed
With some unsaved valid changes, navigating between non-advanced tab is keeping the bottom toolbar (with the save button) always shown.

But when navigating to advanced tab, the toolbar disappear for a spit-second, before reappearing

2024-09-23 22:58 UTC, bonustrack approved these changes
tACK

2024-09-24 06:00 UTC, wa0x6e requested changes
Looks like the dirty state of the sub-spaces is only looking at the number of spaces.

Example:

- My space already 3 sub-spaces
- I remove 1 space -> SAVE button shows up
- I add another different space -> SAVE button disappear

2024-09-24 07:41 UTC, wa0x6e approved these changes
tAck

2024-09-24 07:42 UTC, merged