feat: add Proposal settings (excl. validation)
snapshot-labs/sx-monorepo pull request #832
Opened 2024-09-30 14:44 UTC by Sekhmet

### Summary

This PR adds proposal settings (excluding validation as this will be similar to proposal validation so it will be done in single PR).

### How to test

1. Go to your offchain space settings.
2. You can modify proposal settings.

### Screenshot

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/8e0570d1-24f2-4039-8ce5-cb567c4a7fa8">

2024-09-30 20:59 UTC, wa0x6e requested changes
After dirtying the "guidelines" input with something invalid, the input stay in the error state even after clearing its content

2024-09-30 21:10 UTC, wa0x6e requested changes
When errored, this tab does not show the bottom toolbar with the reset button

2024-10-01 06:04 UTC, ChaituVR reviewed
tAck

2024-10-01 07:35 UTC, Sekhmet commented
Most things didn't trigger bottom bar with reset, but I think it makes sense to do, now made it so every page with internal validation will trigger bottom bar with error with reset.

2024-10-01 07:35 UTC, Sekhmet commented on apps/ui/src/views/Space/Settings.vue
> +          !hasProposalErrors &&
Added in this PR.

2024-10-01 10:41 UTC, wa0x6e approved these changes
tAck,
but we still have the global issue about form error state not persisting after a tab change. Not sure that adding a fix on each form is the way, may be better to ignore them for now and wait for the dirty composable

2024-10-01 11:03 UTC, merged