feat: add link to label
snapshot-labs/sx-monorepo pull request #924
Opened 2024-10-22 17:12 UTC by wa0x6e

### Summary

Closes: #

### How to test

1.

### To-Do

- [ ]

2024-10-23 03:45 UTC, ChaituVR requested changes

2024-10-23 03:45 UTC, ChaituVR commented on apps/ui/src/components/ProposalLabels.vue
> +              query: { 'labels[]': label.id }
we can use `label` instead
<img width="303" alt="Untitled 7" src="https://github.com/user-attachments/assets/7eae9f54-788a-48a3-95a3-4f24348dd329">

2024-10-23 03:45 UTC, ChaituVR commented on apps/ui/src/components/Ui/ProposalLabel.vue
> +    :to="to"
Maybe it would be better to handle this in AppLink. If `to` doesn't exist, it use `div` instead?

2024-11-04 12:56 UTC, bonustrack approved these changes
tACK

2024-11-04 13:06 UTC, ChaituVR approved these changes
utAck (tested it previously)

2024-11-22 10:05 UTC, bonustrack commented
Can we merge this one? @wa0x6e

2024-11-22 10:07 UTC, wa0x6e commented
No, the main pr was reverted, waiting for a fix (on checkpoint I think)

On Fri, Nov 22, 2024 at 18:05 Less ***@***.***> wrote:

> Can we merge this one? @wa0x6e <https://github.com/wa0x6e>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/snapshot-labs/sx-monorepo/pull/924#issuecomment-2493384314>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADZAXONJQMYS3CVX6DKPS32B36XHAVCNFSM6AAAAABQM7L3ACVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJTGM4DIMZRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-27 10:00 UTC, merged