feat: allow any network to be used in Treasuries
snapshot-labs/sx-monorepo pull request #957
Opened 2024-10-31 15:09 UTC by Sekhmet

### Summary

Now any network should be possible to be used in Treasuries on onchain spaces.

Depends on: https://github.com/snapshot-labs/sx-monorepo/pull/946

Closes: https://github.com/snapshot-labs/sx-monorepo/issues/857

### How to test

1. Go to SX space settings.
2. Create treasuries on some non-SX supported network (Base for example).
3. It shows up in treasuries.

2024-11-04 15:34 UTC, wa0x6e requested changes

2024-11-04 15:34 UTC, wa0x6e commented on apps/ui/src/components/PickerToken.vue
> +            :id="`eip155:${network}:${asset.contractAddress}`"
This icon seems to not always work

Before this pr, it looks like this

![Screenshot 2024-11-05 at 00 32 41](https://github.com/user-attachments/assets/ebd4e1c5-86ed-4f02-a4b4-fe9a948d0750)

After:

![Screenshot 2024-11-05 at 00 32 32](https://github.com/user-attachments/assets/7241c3ec-38e0-4411-ae59-664ed2cc7f29)

2024-11-04 15:41 UTC, wa0x6e commented
Are we planning another refactoring to rename `network` to `chainId` in relevant places ? We currently have something like 

```
:chain-id="treasury.network"
```

which are not straightforward

2024-11-04 15:51 UTC, Sekhmet commented
Yeah, I'd like to refactor it at some point.

2024-11-08 18:09 UTC, bonustrack commented
Looks good, there is just these 2 weird networks that appear (it doesn't appear on snapshot.org):
<img width="464" alt="image" src="https://github.com/user-attachments/assets/23c44bdd-9559-481a-a98b-940824ac311d">

2024-11-24 09:26 UTC, wa0x6e approved these changes
tAck

2024-11-25 07:22 UTC, merged